config/routes.rb
Kepler::Engine.routes.draw do
  root :to => 'models#index'

  match '/graph' => 'models#graph', :as => :graph
  match '/:name' => 'models#show',  :as => :model
end

app/models/kepler/model.rb
module Kepler
  class Model < SimpleDelegator
    def initialize(name)
      super name.constantize
    end

    def sources
      files = Set.new
      __getobj__.methods.each do |name|
        m = __getobj__.method(name).source_location
        next if m.nil?
        files << m.first 
      end
      files.grep /\/app\//
    end

    def table
      __getobj__.inspect =~ /\((.*)\)/
      pairs = $1.split(',').map { |s| s.strip.split(': ') }
      Hash[ pairs ]
    end
  end
end

app/controllers/kepler/application_controller.rb
module Kepler
  class ApplicationController < ActionController::Base
  end
end

app/controllers/kepler/models_controller.rb
module Kepler
  class ModelsController < Kepler::ApplicationController

    def index
    end

    def graph
      require 'railroady'

      diagram = ModelsDiagram.new
      diagram.generate

      graph = diagram.instance_eval { @graph }
      nodes = graph.instance_eval { @nodes }
      links = graph.instance_eval { @edges }

      data = { links: [] }
      data[:nodes] = nodes.map { |type, name, attrs| { name: name } }
      map = Hash[ data[:nodes].each_with_index.map { |d,i| [d[:name], i] } ]
      links.each do |type, from, to, _| 
        source, target = map[from], map[to]
        if source && target
          data[:links] << { source: source, target: target }
        else
          # TODO: figure out what to do about base classes / wherever else this happens
        end
      end
      render :json => data
    end

    def show
      @model = Model.new params[:name]
    end
  end

end

app/helpers/kepler/application_helper.rb
module Kepler
  module ApplicationHelper
    def class_link(klass)
      link_to(klass.name, model_path(klass.name))
    end
    
    def format_source(path)
      CodeRay.scan(File.read(path), :ruby).div(:line_numbers => :table)
    end
  end
end

app/views/kepler/models/index.html.haml
#graph
  #sidebar

  #content

:javascript
  $(function() {
    $.getJSON("#{graph_path}.json", function(data) {
      var graph = new Graph(data);
      graph.draw(640, 500);
    });
  });

app/views/kepler/models/show.html.haml
%h2= @model.name

- @model.reflect_on_all_associations.group_by(&:macro).sort.each do |type, associations|
  %h4= type.to_s.capitalize.gsub '_', ' '
  %ul
    - associations.each do |assoc|
      %li
        = class_link assoc.klass
        - if assoc.through_reflection.present?
          through
          = class_link assoc.through_reflection.klass

%h4 Schema
%table
  %tbody
    - @model.table.each do |name, type|
      %tr
        %td= name
        %td= type

%h4= pluralize(@model.sources.length, 'Source')
- @model.sources.each do |path|
  = path
  = format_source(path).html_safe
- if @model.sources.empty?
  %strong Note:
  search may fail to find a source file if it does not define any new methods.

app/views/layouts/kepler/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kepler</title>
  <%= stylesheet_link_tag    "kepler/application", :media => "all" %>
  <%= javascript_include_tag "kepler/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>